# Generated by Django 5.2.5 on 2025-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course_assignment_payment_enrollment_adminearning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_image',
            field=models.ImageField(null=True, upload_to='Media/course_image'),
        ),
    ]
