# Generated by Django 5.2.5 on 2025-08-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_course_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
