# Generated by Django 5.2.5 on 2025-09-17 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_language_course_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
