# Generated by Django 5.2.5 on 2025-09-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_payment_order_id_alter_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], default='Failed', max_length=20),
        ),
    ]
