# Generated by Django 5.2.5 on 2025-09-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed')], default='failed', max_length=20),
        ),
    ]
