# Generated by Django 5.2.5 on 2025-09-21 08:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_submission_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=app.models.video_upload_path),
        ),
    ]
