# Generated by Django 5.2.5 on 2025-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_video_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
    ]
