# Generated by Django 5.2.5 on 2025-10-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_teacherapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='contact_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
